#!/bin/bash

# Copyright (C) 2014
# David A. C. Beck
# dacb@u.washington.edu
# Chemical Engineering & eScience Institute
# University of Washington, Seattle
#
# Date: 12/02/2014
# See version and usage information below
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA

PROGNAME=${0##*/}
PROGVERSION=0.1.0

HOME=`dirname $0`

usage()
{
cat << EOF

Usage: $0 [options] <reference genome fasta> <reference genome genbank> <assembly fasta>

This script performs a suite of analyses of a genome assembly against a reference genome.

Options:
EOF
cat << EOF | column -s\& -t
   -h|--help & Show this message
   -v|--version & Show version information
   -d|--database & Name of database <default is BA2R>
   -t|--threads & Number of threads to use for BLAST <default is 1>
   -s|--skip & Skip BLAST if files exist

EOF
}

defined()
{
[ "${!1-one}" == "${!1-two}" ]
}

is_file_readable()
{
	local file=$1
	if [ ! -r $file ]; then
		echo "$0: unable to read file: $file"
		exit 1
	fi
}

is_command_available()
{
	local command=$1
	command -v $command >/dev/null 2>&1 || { echo >&2 "$PROGNAME requires '$command' to be in the current path.  Aborting."; exit 1; }
}

setup_temp_file()
{
	local tmp=`basename $0`
	TMPFILE=`mktemp -q /tmp/${tmp}.XXXXXX`
	if [ $? -ne 0 ]; then
		echo "$0: unable to create temporary file"
		exit 1
	fi
}

blast6_file_to_db()
{
	local db=$1
	local table=$2
	local file=$3
	echo "* $file to $table in $db"
	cat << EOF | sqlite3 $db
DROP TABLE IF EXISTS $table;
CREATE TABLE $table (
	qseqid varchar(128) NOT NULL,
	sseqid varchar(128) NOT NULL,
	pident FLOAT NOT NULL,
	length INTEGER UNSIGNED NOT NULL,
	mismatch INTEGER UNSIGNED NOT NULL,
	gapopen INTEGER UNSIGNED NOT NULL,
	qstart INTEGER UNSIGNED NOT NULL,
	qend INTEGER UNSIGNED NOT NULL,
	sstart INTEGER UNSIGNED NOT NULL,
	send INTEGER UNSIGNED NOT NULL,
	evalue DOUBLE NOT NULL,
	bitscore INTEGER UNSIGNED NOT NULL
);
.mode tabs
.import $file $table
CREATE INDEX ${table}_qseqid ON $table (qseqid);
CREATE INDEX ${table}_sseqid ON $table (sseqid);
EOF
}

extract_tab_from_db()
{
	local db=$1
	local table=$2
	local tab=$table.tab
	echo "* $table from $db to $tab"
	cat << EOF | sqlite3 $DATABASE > $tab
.mode tabs
SELECT * FROM $table WHERE evalue = 0 ORDER BY qseqid, sseqid, qstart;
EOF
}

# parse arguments
SHORTOPTS="hvsd:t:"
LONGOPTS="help,version,skip,database:,threads:"
ARGS=$(getopt -s bash --options $SHORTOPTS --longoptions $LONGOPTS --name $PROGNAME -- "$@")
if [ $? != 0 ]; then usage; exit 1; fi
eval set -- "$ARGS"
# loop through options
while true; do
        case $1 in
                -h|--help)
                        usage
                        exit 0
                        ;;
                -v|--version)
                        echo "$PROGVERSION"
                        exit 0
                        ;;
                -d|--database)
                        DATABASE=$2
                        shift 2
                        ;;
		-t|--threads)
			THREADS=$2
			shift 2
			;;
		-s|--skip)
			SKIP=1
			shift
			;;
                --) 
                        shift
                        break
                        ;;
                *) 
                        shift
                        break
                        ;;
        esac
done

if [ "$#" -ne 3 ]; then
        usage
        exit 1
fi

defined DATABASE || DATABASE=BA2R.db
defined THREADS || THREADS=1

REF_FASTA=$1
is_file_readable $REF_FASTA
REF_GENBANK=$2
is_file_readable $REF_GENBANK
ASM_FASTA=$3
is_file_readable $ASM_FASTA

FA2SQL=$HOME/fa2sql.awk
is_file_readable $FA2SQL
GB2SQL=$HOME/gb2sql.awk
is_file_readable $GB2SQL

is_command_available sqlite3
is_command_available makeblastdb
is_command_available blastn

echo "configuration:"
echo "* reference FASTA   = $REF_FASTA"
echo "* reference GENBANK = $REF_GENBANK"
echo "* assembly FASTA    = $ASM_FASTA"
echo "* database name     = $DATABASE"
echo "----"

echo "populating the database from input files:"
if [ -e $DATABASE ]; then
	echo "* skipping loading the database"
else
	echo "* loading $REF_FASTA to table ref_seqs"
	awk -f $FA2SQL -v create_table=1 -v table="ref_seqs" $REF_FASTA | sqlite3 $DATABASE
	echo "* loading $REF_GENBANK to table ref_genes"
	awk -f $GB2SQL -v create_table=1 -v table="ref_genes" $REF_GENBANK | sqlite3 $DATABASE
	echo "* loading $ASM_FASTA to table asm_seqs"
	awk -f $FA2SQL -v create_table=1 -v table="asm_seqs" $ASM_FASTA | sqlite3 $DATABASE
fi
echo "----"

echo "making BLAST databases:"
if [ ! -z "$SKIP" ] && [ -e reference.nsq ]; then
	echo "* skipping makeblastdb for $REF_FASTA"
else
	echo "* $REF_FASTA"
	makeblastdb -in $REF_FASTA -dbtype nucl -title "Reference genome" -parse_seqids -hash_index -out reference -logfile reference.makeblastdb.log
fi
if [ ! -z "$SKIP" ] && [ -e assembled.nsq ]; then
	echo "* skipping makeblastdb for $ASM_FASTA"
else
	echo "* $ASM_FASTA"
	makeblastdb -in $ASM_FASTA -dbtype nucl -title "Assembled genome" -parse_seqids -hash_index -out assembled -logfile assembled.makeblastdb.log
fi

echo "running BLASTN: "
if [ ! -z "$SKIP" ] && [ -e asm_vs_ref.blast6 ]; then
	echo "* skipping BLASTN for query = $ASM_FASTA and subject = $REF_FASTA"
else
	echo "* BLASTing $ASM_FASTA against reference genome"
	blastn -db reference -query $ASM_FASTA -outfmt 6 -num_threads $THREADS > asm_vs_ref.blast6
fi
if [ ! -z "$SKIP" ] && [ -e ref_vs_asm.blast6 ]; then
	echo "* skipping BLASTN for query = $REF_FASTA and subject = $ASM_FASTA"
else
	echo "* BLASTing $REF_FASTA against assembled genome"
	blastn -db assembled -query $REF_FASTA -outfmt 6 -num_threads $THREADS > ref_vs_asm.blast6
fi
echo "loading results to SQL table: "
blast6_file_to_db $DATABASE asm_vs_ref asm_vs_ref.blast6
blast6_file_to_db $DATABASE ref_vs_asm ref_vs_asm.blast6
echo "----"

echo "extracting tables for processing:"
extract_tab_from_db $DATABASE asm_vs_ref 
extract_tab_from_db $DATABASE ref_vs_asm
echo "processing table:"
